---
- name: Ensure existing CA directory
  file:
    path: "{{ pki_ca_dir }}"
    state: directory

- name: Create the CA private key
  openssl_privatekey:
    backup: yes
    type: "{{ pki_key_type }}"
    curve: "{{ pki_key_curve }}"
    path: "{{ pki_ca_dir }}/ca-key.pem"

- name: Create the CA CSR
  openssl_csr:
    path: "{{ pki_ca_dir }}/ca.csr"
    privatekey_path: "{{ pki_ca_dir }}/ca-key.pem"
    basic_constraints:
      - "CA:TRUE"
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
      - cRLSign
      - digitalSignature
    key_usage_critical: yes
    create_subject_key_identifier: yes
    common_name: Root CA {{ pki_name }}

- name: Create the CA certificate
  openssl_certificate:
    provider: selfsigned
    selfsigned_create_subject_key_identifier: always_create
    path: "{{ pki_ca_dir }}/ca.pem"
    privatekey_path: "{{ pki_ca_dir }}/ca-key.pem"
    csr_path: "{{ pki_ca_dir }}/ca.csr"
    backup: yes
