---
- name: Copy CA certificate file
  copy:
    src: "{{ pki_ca_dir }}/ca.pem"
    dest: "{{ dest }}"
    owner: "{{ owner | default(omit) }}"
    group: "{{ group | default(omit) }}"
    mode: "{{ mode | default(omit) }}"
